linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - unconvert
    - unused 
