language: go

sudo: true

go:
  - "1.13.x"

install:
  # Install `golangci-lint` using their installer script
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  # Install `cover` and `goveralls` without `GO111MODULE` enabled so that we
  # don't download ct-woodpecker dependencies and just put the tools in our
  # gobin.
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls
  - go install -v -mod=vendor ./...

before_script:
  - ct-test-srv -config ./test/config/cttestsrv.json &
  - chmod 0600 test/config/db_password

script:
  - set -e
  - golangci-lint run
  - docker-compose up -d mysql
  - go test -mod=vendor -v -race -covermode=atomic -coverprofile=coverage.out -tags=integration ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - ct-woodpecker -config ./test/config/ct-woodpecker.localdev.json &
  - sleep 30s; killall ct-woodpecker
