CREATE TABLE IF NOT EXISTS SubmittedCerts(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LogID BIGINT NOT NULL,
    Cert BLOB NOT NULL,
    SCT BLOB NOT NULL,
    Timestamp BIGINT NOT NULL,
    Seen DATETIME
);

CREATE TABLE IF NOT EXISTS LogIndexes(
    LogID BIGINT PRIMARY KEY,
    LogIndex BIGINT NOT NULL
);