CREATE TABLE IF NOT EXISTS SubmittedCerts(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    LogID BIGINT NOT NULL,
    Cert BLOB NOT NULL,
    SCT BLOB NOT NULL,
    Timestamp DATETIME NOT NULL,
    Seen DATETIME,
    PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS LogIndexes(
    LogID BIGINT NOT NULL,
    Index BIGINT NOT NULL,
    PRIMARY KEY (LogID)
);