CREATE TABLE IF NOT EXISTS SubmittedCerts(
    `ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `LogID` BIGINT NOT NULL,
    `Cert` BLOB NOT NULL,
    `SCT` BLOB NOT NULL,
    `Timestamp` BIGINT NOT NULL,
    `Seen` DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS LogIndexes(
    `LogID` BIGINT PRIMARY KEY,
    `LogIndex` BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
