global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/woodpecker_alerts.yml"

scrape_configs:
  - job_name: ctwoodpecker
    scrape_interval: 30s
    static_configs:
      - targets: ['127.0.0.1:1971']
        labels:
          group: ctwoodpecker

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:9093"
