{
 "title": "ct-woodpecker",
 "description": "ct-woodpecker pokes holes in logs. It is a tool for monitoring a Certificate Transparency log for operational problems.",
 "tags": [ "ct" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "log", "label": "log", "query": "sth_age" },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Unincorporated SCTs",
   "type": "singlestat",
   "description": "Number of SCTs that haven't been matched to log entries",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "unincorporated_certs" }
   ]
  },
  {
   "title": "Stored SCTs",
   "type": "singlestat",
   "description": "Count of unique SCTs we have retrieved and stored in the database",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "stored_scts" }
   ]
  },
  {
   "title": "Current STH Timestamp",
   "type": "singlestat",
   "description": "Elapsed time since observed CT log signed tree head (STH) timestamp",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sth_timestamp{uri=~\".*${log}.*\"}"
    }
   ]
  },
  {
   "title": "Histogram STH Consistency Proof Latency",
   "type": "graph",
   "description": "Latency requesting CT signed tree head (STH) consistency proof",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(sth_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sth_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(sth_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le))",
     "legendFormat": "99.9%"
    }
   ]
  },
  {
   "title": "Histogram STH Observed Latency",
   "type": "graph",
   "description": "Latency observing CT log signed tree head (STH)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(sth_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sth_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(sth_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le))",
     "legendFormat": "99.9%"
    }
   ]
  },
  {
   "title": "Histogram Certificate Submission",
   "type": "graph",
   "description": "Latency submitting certificate chains to CT logs",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cert_submit_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le,precert))",
     "legendFormat": "90% Precert: {{ precert }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cert_submit_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le,precert))",
     "legendFormat": "95% Precert: {{ precert }}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(cert_submit_latency_bucket{uri=~\".*${log}.*\"}[5m])) by (le,precert))",
     "legendFormat": "99.9% Precert: {{ precert }}"
    }
   ]
  },
  {
   "title": "STH Inconsistencies",
   "type": "graph",
   "description": "Errors verifying STH to STH consistency from log",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sth_inconsistencies{uri=~\".*${log}.*\"}",
     "legendFormat": "{{ uri }}"
    }
   ]
  },
  {
   "title": "STH Retrieval Errors",
   "type": "graph",
   "description": "Errors retrieving STH from log",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sth_failures{uri=~\".*${log}.*\"}",
     "legendFormat": "{{ uri }}"
    }
   ]
  },
  {
   "title": "STH Age",
   "type": "graph",
   "description": "Elapsed time since observed CT log signed tree head (STH) timestamp",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sth_age{uri=~\".*${log}.*\"}",
     "legendFormat": "{{ uri }}"
    }
   ]
  },
  {
   "title": "Certificate Submission Status",
   "type": "graph",
   "description": "Count of results from submitting certificate chains to CT logs, sliced by status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cert_submit_results{uri=~\".*${log}.*\"}",
     "legendFormat": "{{ uri }} Status: {{ status }} Precert: {{ precert }} Duplicate: {{ duplicate }} "
    }
   ]
  }
 ]
}