name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Install cover
      run: go install golang.org/x/tools/cmd/cover@latest

    - name: Run ct-test-srv
      run: ct-test-srv -config ./test/config/cttestsrv.json &

    - name: Chmod db_password
      run: chmod 0600 test/config/db_password

    - name: build
      run: go build ./...

    - name: mysql
      run: docker-compose up -d mysql

    - name: test
      run: go test -mod=vendor -race -covermode=atomic -coverprofile=coverage.out -tags=integration ./...

    - name: ct-woodpecker
      run: ct-woodpecker -config ./test/config/ct-woodpecker.localdev.json &

    - name: kill
      run: sleep 30s; killall ct-woodpecker
